version: '3'
services:
  orbit_graph:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./orbit_graph:/app/orbit_graph
      # TODO(gitbuda): Huge hack but during hackathon all is allowed!
      - /home/ubuntu/frontend:/frontend
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687
    # TODO(gitbuda): Move stuff from deploy to one docker compose.
    # depends_on:
    #   - memgraph
    networks:
      - orbit-graph
networks:
  orbit-graph:
    name: custom
    driver: bridge
