---
- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Install basic packages on Debian systems
  become: yes
  apt:
    pkg:
    - git
    - python3
    - python3-pip

- name: Install pip packages
  become: yes
  pip:
    name:
      - docker
      - docker-compose
...
