---
- hosts: orbitgraph
  become: true
  roles:
    - basic
    - docker
    - role: docker_upload
      vars:
        docker_image_control_node_path: "{{ playbook_dir }}/../memgraph/memgraph-1.6.1-orbit.tar"
        docker_image_host_path: "/home/{{ ansible_user }}/memgraph-1.6.1-orbit.tar"
        docker_image_name: "memgraph-1.6.1-orbit"
    - orbit_graph
...
