export const MUTATION_CONSTANTS = {
  SET_MEMBER_GRAPH: "SET_MEMBER_GRAPH",
  SET_USERNAMES: "SET_USERNAMES",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_ACTIVITIES: "SET_ACTIVITIES",
  SHOW_USER_DETAILS: "SHOW_USER_DETAILS",
  DISPOSE_USER_DETAILS: "DISPOSE_USER_DETAILS",
  SET_IS_FETCHING_USER_DETAILS: "SET_IS_FETCHING_USER_DETAILS",
}