---
- name: Start Orbit Graph Services
  community.docker.docker_compose:
    project_name: orbit_graph
    definition:
      version: "3"
      services:
        zookeeper:
          image: 'bitnami/zookeeper:3.6.3-debian-10-r33'
          ports:
            - '2181:2181'
          environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
          networks:
            - orbit-graph
        kafka:
          image: 'bitnami/kafka:2.8.0-debian-10-r49'
          ports:
            - '9092:9092'
          environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://ec2-34-241-136-34.eu-west-1.compute.amazonaws.com:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
          depends_on:
            - zookeeper
          networks:
            - orbit-graph
        memgraph:
          image: 'memgraph/memgraph:1.6.0-community'
          entrypoint: ['/usr/lib/memgraph/memgraph', '--telemetry-enabled=false', '--kafka-bootstrap-servers=kafka:9092', '--log-level=TRACE']
          ports:
            - '7687:7687'
          networks:
            - orbit-graph
      networks:
        orbit-graph:
          name: custom
          driver: bridge

- name: Copy backend code
  synchronize:
    src: ../backend/
    dest: /home/{{ ansible_user }}/backend
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=ve3"
      - "--exclude=__pycache__"
      - "--exclude=htmlcov"

- name: Copy modules code
  synchronize:
    src: ../modules/
    dest: /home/{{ ansible_user }}/modules
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=ve3"
      - "--exclude=__pycache__"
      - "--exclude=htmlcov"

- name: Start backend service
  community.docker.docker_compose:
    project_name: orbit_graph
    project_src: /home/{{ ansible_user }}/backend
    build: yes
...
