---
- name: Start Orbit Graph Services
  community.docker.docker_compose:
    project_name: orbit_graph
    definition:
      version: "3"
      services:
        zookeeper:
          image: 'bitnami/zookeeper:3.6.3-debian-10-r33'
          ports:
            - '2181:2181'
          environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
          networks:
            - orbit-graph
        kafka:
          image: 'bitnami/kafka:2.8.0-debian-10-r49'
          ports:
            - '9092:9092'
          environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://ec2-34-241-136-34.eu-west-1.compute.amazonaws.com:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
          depends_on:
            - zookeeper
          networks:
            - orbit-graph
        memgraph:
          image: 'memgraph-1.6.1-orbit'
          volumes:
            - '/home/{{ ansible_user }}/modules:/query_modules'
          entrypoint: [
            '/usr/lib/memgraph/memgraph',
            '--telemetry-enabled=false',
            '--query-modules-directory=/usr/lib/memgraph/query_modules,/query_modules',
            '--query-execution-timeout-sec=1200',
            '--kafka-bootstrap-servers=kafka:9092',
            '--log-level=TRACE',
            '--also-log-to-stderr'
          ]
          # TODO(gitbuda): Figure out how to pass these environment variables into the query module.
          # environment:
          #   - ORBIT_GRAPH_GITHUB_TOKEN=
          #   - ORBIT_GRAPH_TWITTER_TOKEN=
          ports:
            - '7687:7687'
          networks:
            - orbit-graph
      networks:
        orbit-graph:
          name: custom
          driver: bridge

- name: Copy backend code
  synchronize:
    src: ../backend/
    dest: /home/{{ ansible_user }}/backend
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=ve3"
      - "--exclude=__pycache__"
      - "--exclude=htmlcov"

- name: Copy modules code
  synchronize:
    src: ../modules/
    dest: /home/{{ ansible_user }}/modules
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=ve3"
      - "--exclude=__pycache__"
      - "--exclude=htmlcov"

- name: Delete content & directory
  file:
    state: absent
    path: /home/{{ ansible_user }}/frontend/

- name: Copy frontend code
  synchronize:
    src: ../frontend/dist/
    dest: /home/{{ ansible_user }}/frontend
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=ve3"
      - "--exclude=__pycache__"
      - "--exclude=htmlcov"
      - "--exclude=node_modules"

# TODO(gitbuda): Ensure right permissions for the modules/data directory.

- name: Start backend service
  community.docker.docker_compose:
    project_name: orbit_graph
    project_src: /home/{{ ansible_user }}/backend
    build: yes
    nocache: yes

- name: Start balancer
  tags: balancer
  community.docker.docker_compose:
    project_name: orbit_graph
    definition:
      version: "3"
      services:
        balancer:
          image: 'nginx-orbit'
          ports:
            - '443:443'
          networks:
            - orbit-graph
      networks:
        orbit-graph:
          name: custom
          driver: bridge
...
